# Configuration file
"%dev":
  conf:
    app:
      url:
        frontend: http://localhost:4200
      cookie:
        seguro: false
        dominio-api-recurso: localhost
        dominio-api-seguranca: localhost
    db:
      nome: app_security_db
      host: localhost
      port: 5434
      usuario: postgres
      senha: "123456"

  quarkus:
    hibernate-orm:
      log:
        sql: true

"%prod":
  conf:
    app:
      url:
        frontend: ${URL_APLICACAO_FRONTEND}
      cookie:
        seguro: true
        dominio-api-recurso: api-gestao-associados.herokuapp.com
        dominio-api-seguranca: app-seguranca-api.herokuapp.com


    db:
      nome: ${DATABASE_NAME}
      host: ${DATABASE_HOST}
      port: ${DATABASE_PORT}
      usuario: ${DATABASE_USER}
      senha: ${DATABASE_PASSWORD}
    
quarkus:
  http:
    cors:
      ~: true
      origin: ${conf.app.url.frontend}
      access-control-allow-credentials: true
    port: 8081

  datasource:
    db-kind: postgresql
    username: ${conf.db.usuario}
    password: ${conf.db.senha}
    jdbc:
      url: jdbc:postgresql://${conf.db.host}:${conf.db.port}/${conf.db.nome}
      min-size: 4
      max-size: 16

  flyway:
    migrate-at-start: true
    schemas: public
    table: flyway_versoes
    locations: db/migration

  smallrye-jwt:
    enabled: true

# mp:
#   jwt:
#     verify:
#       issuer: app-security
#       publickey:
#         location: META-INF/resources/publicKey.pem

smallrye:
  jwt:
    token:
      header: Cookie
      cookie: tokenServico